#Dev Mode?
development: true

# Getting Started
title: 	"Mike Key"
tagline: "Musing on life, parenthood, work and self improvement"
description: "I'm Mike, a 30 something digital nomad. Balancing, life, work and play while on the road."
email:  "mike@mk3y.com"

# Site Config
baseurl: ""
url: "https://mk3y.com"

# Dependencies
markdown: kramdown
# highlighter: pygments

# Permalinks
permalink: pretty

#Display Settings
paginate: 5
paginate_path: "page:num"

# Custom vars
icon:       "/assets/img/icon.png"
cover:      "https://lh3.googleusercontent.com/kKsizieETQ0J1rc5YSIB-lEs1msXf8dAj70JtqSqVFA=w1232-h790-no"

# Extra Gems
gems:
  - jekyll-sitemap

# Build settings
timezone: America/New York
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Assets Pipeline
sass:
 sass_dir: "assets/css/"
 style: :compressed