# Getting Started
title: 	"Mike Key"
description: "Mike Key is a freelance full-stack developer. This is a collection of writings on web development, enterpernuership and personal development."
email:  "mike@mk3y.com"

# Site Config
baseurl: ""
url: "https://mk3y.com"

# Display settings
markdown: kramdown
highlighter: pygments
permalink: pretty
lsi: false
paginate: 5
paginate_path: "page:num"

# Extra Gems
gems:
  - jekyll-sitemap

# Build settings
timezone: America/New York
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Assets Pipeline
sass:
 sass_dir: "assets/css/"
 style: :compressed