title: 	"Mike Key - MK3Y.com"
tagline: "Musing on life, work and travel"
description: "We're 30 somethings working, traveling and investing from the road while raising two kids"
email:  "mike@mk3y.com"
baseurl: ""
url: "https://mk3y.com"

markdown: kramdown

paginate:      5
paginate_path: /blog/:num/

permalink:     /:title/

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - README.md
    - CNAME
    - Gemfile

sass:
    sass_dir: "_dev/sass/"
    style: compressed

 # Custom vars
icon:       "/assets/img/icon.png"
hero:      "/images/bg.jpg"
