#Dev Mode?
development: true

# Getting Started
title: 	"MIKE KEY"
tagline: "Musings of a Husband, Father, Programer & Athesist"
description: "Mike Key is a freelance full-stack developer. This is a collection of writings on web development, enterpernuership and personal development."
email:  "mike@mk3y.com"


# Site Config
baseurl: ""
url: "https://mk3y.com"

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

#Display Settings
paginate: 5
paginate_path: "page:num"

# Custom vars
icon:       /assets/img/icon.png
cover:      /assets/img/cover.jpg

# Extra Gems
gems:
  - jekyll-sitemap

# Build settings
timezone: America/New York
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Assets Pipeline
sass:
 sass_dir: "assets/css/"
 style: :compressed