title: 	"MK3Y - Mike & JorDanee Key"
tagline: "Musing on life, work and travel"
description: "We're 30 somethings working, traveling and investing from the road while raising two kids"
email:  "mike@mk3y.com"
baseurl: ""
url: "https://mk3y.com"

markdown: kramdown

paginate:      3
paginate_path: /blog/:num/

permalink:     /:title/

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - README.md
    - CNAME
    - Gemfile

sass:
    sass_dir: "assets/_sass/"
    style: compressed

 # Custom vars
icon:       "/assets/img/icon.png"
cover:      "https://lh3.googleusercontent.com/kKsizieETQ0J1rc5YSIB-lEs1msXf8dAj70JtqSqVFA=w1232-h790-no"
