title: 	"Mike Key - MK3Y.com"
tagline: "Musing on Business, Self Improvement, Life and Travel"
description: "Father. Polymath. Autodidact. I read old books, lift heavy things, eat paleo and drink whiskey"
email:  "mike@mk3y.com"
baseurl: ""
url: "https://mk3y.com"

markdown: kramdown

paginate:      5
paginate_path: /blog/:num/

permalink:     /:title/

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - README.md
    - CNAME
    - Gemfile

sass:
    sass_dir: "_dev/sass/"
    style: compressed

 # Custom vars
icon:       "/assets/img/icon.png"
hero:      "/images/bg.jpg"
