title: 	"Mike Key"
email: 	"mike@mk3y.com"
description: "Musings of Michael Key"
baseurl: ""
url: "http://mk3y.com"

# Development settings
development: false
debug: false

# Display settings
markdown: kramdown
permalink: pretty
lsi: false

# Pagination
paginate: 5
#paginate_path: "page:num"

# Build settings
timezone: America/New York
future: false
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Theme Settings
theme_reading_time: true


# Extra gems to have fancy things.
gems:
  - jekyll-sitemap

# Asset Pipeline settings
sass:
 sass_dir: "assets/css/"
 style: :compressed